# Use an official Node.js Alpine runtime as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR app

# Install Redis
RUN apk add --no-cache redis

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your application's source code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Start Redis and your Node.js application
CMD ["sh", "-c", "redis-server --daemonize yes && npm start"]